services:
    mappo-pa:
        build: 
            dockerfile: ./Dockerfile
        container_name: mappo-pa
        restart: unless-stopped
        command: /bin/sh -c 'deno run serve-otel-pa'
        ports:
            - "9901:9900"